export const SET_PRE_GAME = "SET_PRE_GAME";
export const SET_IN_GAME = "SET_IN_GAME";
export const SET_POST_GAME = "SET_POST_GAME";

export const SET_PRE_ANSWER = "SET_PRE_ANSWER";
export const SET_POST_ANSWER = "SET_POST_ANSWER";

export const CHANGE_POINT_AMOUNT = "CHANGE_POINT_AMOUNT";
export const ZERO_POINTS = "ZERO_POINTS";

export const APPEND_SOLVE_TIME = "APPEND_SOLVE_TIME";
export const RESET_SOLVE_TIMES = "RESET_SOLVE_TIMES";
export const CHANGE_GRIDS_SOLVED = "CHANGED_GRIDS_SOLVED";
export const UPDATE_BASE_SCORE = "UPDATE_BASE_SCORE";
export const UPDATE_PENALTIES = "UPDATE_PENALTIES";
export const UPDATE_TIME_BONUS = "UPDATE_TIME_BONUS";
